use version constant, improve error logging and increment version again.
When trying the live version we got the following error message:
DOMException: The operation failed because the stored database is a higher version than the version requested.